
export const projects = [
    {
        title: 'Car Bike Marketplace',
        description: 'A full-stack vehicle marketplace platform built with Next.js, TypeScript, and Tailwind CSS.',
        technologies: ['Next.js', 'TypeScript', 'Tailwind CSS','Expressjs', 'MongoDB'],
        githubLink: 'https://github.com',
        demoLink: 'https://carbikemarket.com',
        image: '/og-carbikemarket.png',
    },
    {
        title: 'S raj engineering',
        description: 'A full-stack bakery equipment listing platform built with Next.js, TypeScript, and Tailwind CSS.',
        technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
        githubLink: 'https://github.com',
        demoLink: 'https://srajengineering.in/',
        image: '/s-rajengineering.png',
    },
    {
        title: 'FOCUS INSTITUTE',
        description: 'A full-stack safety institute management platform built with next.js, TypeScript, Express, MongoDB, better-auth',
        technologies: ['React', 'Node.js', 'MongoDB', 'Express.js','better-auth'],
        githubLink: 'https://github.com',
        demoLink: 'https://focusdeo.in/',
        image: '/focussite-logo.webp',
    },
    {
        title: 'Portfolio Website',
        description: 'My personal portfolio website showcasing my projects and skills.',
        technologies: ['Next.js', 'Tailwind CSS', 'Framer Motion'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/portfolio-website.jpg',
    },
    {
        title: 'Blog Platform',
        description: 'A blogging platform with user authentication and markdown support.',
        technologies: ['Gatsby', 'GraphQL', 'Contentful'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/blog-website.jpeg',
    },
    {
        title: 'Weather App',
        description: 'A weather application that provides real-time weather updates.',
        technologies: ['React', 'OpenWeatherMap API'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/weather-app.png',
    },
    {
        title: 'Chat Application',
        description: 'A real-time chat application using WebSocket technology.',
        technologies: ['React', 'Node.js', 'Socket.io'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/chat-app.png',
    },
    {
        title: 'Recipe Finder',
        description: 'A recipe search application using the Edamam API.',
        technologies: ['React', 'Edamam API'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/recipe-finder.png',
    },
    {
        title: 'Expense Tracker',
        description: 'A personal finance tracker to manage expenses and income.',
        technologies: ['React', 'Firebase'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/expense-tracker.webp',
    }
];